name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Images
      run: |
        docker build -t ${{ talk2harishsingh@gmail.com }}/nginx-custom:latest ./frontend
        docker build -t ${{ talk2harishsingh@gmail.com }}/php-fpm-custom:latest ./backend
        docker build -t ${{ talk2harishsingh@gmail.com }}/mysql-custom:latest ./database
        docker push ${{ talk2harishsingh@gmail.com }}/nginx-custom:latest
        docker push ${{ talk2harishsingh@gmail.com }}/php-fpm-custom:latest
        docker push ${{ talk2harishsingh@gmail.com }}/mysql-custom:latest

    - name: Configure Kubernetes
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        kubectl apply -f k8s/
